name: Run appium tests in github runner

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: checkout
        uses: actions/checkout@v2

      - name: Run the tests
        run: 
            mvn clean test -Pall     
          
