name: Run Android Tests in GitHub Runner

on: push

jobs:
  run-mobile-tests:
    runs-on: macos-12

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &
          echo "Waiting for Appium server to start..."
          sleep 15  # Adjust this if needed, to give Appium enough time to start

      - name: Run Appium Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Pandroid
