name: testing

on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s -H "Authorization: token ${{ github.token }}" -X POST -d '{"body": "Your Message to Comment"}' "https://api.github.com/repos/amuthansakthivel/SeleniumAppiumTestsInGithubRunners/issues/42/comments"
       
