name: testing

on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s -H "Authorization: token ${{ github.token }}" -X POST -d '{"body": "👋 Playwright tests failed "}' "https://api.github.com/repos/amuthansakthivel/SeleniumAppiumTestsInGithubRunners/issues/42/comments"
       
