name: run the workflow on PR comment

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && github.event.issue.number == 2 && contains(github.event.comment.body, 'check')}}
    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - run: echo "${{ github.event.issue.number }}"
      - run: echo "${{ github.event.issue.tag }}"
      - run: echo "${{ github.event.issue.body }}"

